# Generated by Django 3.2.22 on 2025-07-20 13:31

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(null=True)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'patients',
                'db_table': 'app_patient_patient',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('physical_exam', models.TextField(blank=True, null=True)),
                ('para_clinic', models.TextField(blank=True, null=True)),
                ('manipulation', models.BooleanField(default=False)),
                ('needle', models.BooleanField(default=False)),
                ('injection', models.BooleanField(default=False)),
                ('emg', models.BooleanField(default=False)),
                ('physiotherapy', models.BooleanField(default=False)),
                ('procedure', models.TextField(blank=True, null=True)),
                ('datetime', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
                ('payment', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_patient.patient')),
            ],
            options={
                'verbose_name_plural': 'visits',
                'db_table': 'app_patient_visit',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_list', models.TextField(blank=True, null=True)),
                ('datetime', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prescriptions')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_patient.patient')),
            ],
            options={
                'verbose_name_plural': 'prescriptions',
                'db_table': 'app_patient_prescription',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.CharField(blank=True, max_length=11, null=True)),
                ('number2', models.CharField(blank=True, max_length=11, null=True)),
                ('number3', models.CharField(blank=True, max_length=11, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_patient.patient')),
            ],
            options={
                'verbose_name': 'phone number',
                'verbose_name_plural': 'phone numbers',
                'db_table': 'app_patient_phone',
            },
        ),
    ]
